apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eventrecorder-heroku-hook-staging-secrets
  namespace: default
spec:
  secretStoreRef:
    name: cirkul-secret-store-prod
    kind: SecretStore
  data:
  - secretKey: staging.yaml
    remoteRef:
      key: /prod/eventrecorder_heroku_hook/config/staging.yml
  target:
    name: eventrecorder-heroku-hook-staging-secrets
