apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventrecorder-heroku-hook
  namespace: default
  labels:
    app: eventrecorder_heroku_hook
    env: prod
    category: data
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventrecorder_heroku_hook
      env: prod
      category: data
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eventrecorder_heroku_hook
        env: prod
        category: data
    spec:
      containers:
      - name: &container_name eventrecorder-heroku-hook
        image: 016538182541.dkr.ecr.us-east-1.amazonaws.com/eventrecorder_heroku_hook:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: EVENTRECORDER_HEROKU_HOOK_MODE
          value: 'production'
        - name: LIMIT_MAX_REQUESTS
          value: "100000"
        volumeMounts:
        - name: eventrecorder-heroku-hook-secrets
          mountPath: /secrets/eventrecorder_heroku_hook
          readOnly: true
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 256Mi
      restartPolicy: Always
      volumes:
      - name: eventrecorder-heroku-hook-secrets
        secret:
          secretName: eventrecorder-heroku-hook-secrets
